<div class="panel panel-primary size">
  <div class="panel-heading">
    <center><h3 class="panel-title">Formulario de Registro</h3></center>
  </div>
  <div class="panel-body">
      <form id="form_registro" class="form-horizontal" role="form" name="form_registro" method="POST" action='<?=$this->url('application/default',array('controller'=>'index','action'=>'save'))?>'> 
        <div class="form-group">
            <label for="nombre" class="col-lg-4 control-label">Nombre (s): </label>
            <div class="col-lg-6">
                <input type="text" id="nombre" class="form-control" placeholder="Ingrese su nombre" name="nombre">
            </div>
        </div>
        <div class="form-group">
            <label for="apellido_paterno" class="col-lg-4 control-label">Apellido Paterno: </label>
            <div class="col-lg-6">
                <input type="text" id="apellido_paterno" class="form-control" placeholder="Ingrese apellido paterno" name="apellido_paterno">
            </div>
        </div>
        <div class="form-group">
            <label for="apellido_materno" class="col-lg-4 control-label">Apellido Materno </label>
            <div class="col-lg-6">
                <input type="text" id="apellido_materno" class="form-control" name="apellido_materno" placeholder="Ingrese apellido materno">
            </div>
        </div>
        <div class="form-group">
            <label for="fecha_nacimiento" class="col-lg-4 control-label">Fecha de Nacimiento: </label>
            <div class="col-lg-6">
                <input type="text" id="fecha_nacimiento" class="form-control" name="fecha_nacimiento" placeholder="Elija fecha de nacimiento">
            </div>
        </div>
        <div class="form-group">
            <label for="tipo_documento" class="col-lg-4 control-label">Tipo de Documento </label>
            <div class="col-lg-6">
            	<select name="tipo_documento">
            		<option value=1>DNI </option>
			<option value=2>CARNE de Extranjeria </option>
            	</select>
            </div>
        </div>
        <div class="form-group">
            <label for="documento" class="col-lg-4 control-label">Documento: </label>
            <div class="col-lg-6">
                <input type="text" id="documento" class="form-control" name="documento" >
            </div>
        </div>
        <div class="form-group">
            <label for="sexo" class="col-lg-4 control-label">Sexo </label>
            <div class="col-lg-6">
            	<select id="sexo" name="sexo">
            		<option value="F">F </option>
			<option value="M">M</option>
            	</select>
            </div>
        </div>
        <div class="form-group">
            <label for="direccion" class="col-lg-4 control-label">Direccion: </label>
            <div class="col-lg-6">
                <input type="text" id="direccion" class="form-control" name="direccion" >
            </div>
        </div>
        <div class="form-group">
            <label for="email" class="col-lg-4 control-label">Email: </label>
            <div class="col-lg-6">
                <input type="text" id="email" class="form-control" name="email" placeholder="Ingrese corre electronico">
            </div>
        </div>
        <div class="form-group">
            <label for="telefono" class="col-lg-4 control-label">Telefono: </label>
            <div class="col-lg-6">
                <input type="text" id="telefono" class="form-control" name="telefono">
            </div>
        </div>
        <div class="form-group">
            <label for="celular" class="col-lg-4 control-label">Celular: </label>
            <div class="col-lg-6">
                <input type="text" id="celular" class="form-control" name="celular">
            </div>
        </div>
        <div class="form-group">
            <label for="prov_celular" class="col-lg-4 control-label">Prov_Celular: </label>
            <div class="col-lg-6">
                <input type="text" id="prov_celular" class="form-control" name="prov_celular">
            </div>
        </div>
        <div class="form-group">
            <label for="telefono_otro" class="col-lg-4 control-label">Telefono_otro: </label>
            <div class="col-lg-6">
                <input type="text" id="telefono_otro" class="form-control" name="telefono_otro">
            </div>
        </div>
        <div class="form-group">
            <label for="int_tipo" class="col-lg-4 control-label">Tipo Interior: </label>
            <div class="col-lg-6">
                <input type="text" id="int_tipo" class="form-control" name="int_tipo">
            </div>
        </div>
        <div class="form-group">
            <label for="ubigeo" class="col-lg-4 control-label">Ubigeo </label>
            <div class="col-lg-6">
                <input type="text" id="ubigeo" class="form-control" name="ubigeo">
            </div>
        </div>
        <center> 
            <input type="submit" value="Guardar">
            <button id="btncancelar" type="button" class="btn btn-danger">Cancelar</button>
        </center>
    </form>
  </div>
</div>