
<div class="row">

    <div class="col-md-4">
        <form id="form_validar" class="form-horizontal" role="form" method="POST" action='<?=$this->url('application/default',array('controller'=>'index','action'=>'validar'))?>'> 
            <div class="form-group">
                <label for="dni" class="col-lg-4 control-label">Ingrese DNI</label>
                <div class="col-lg-6">
                    <input type="text" id="dni" class="form-control" placeholder="Ingrese su DNI" 
                    name="dni">
                </div>
            </div>
                  <input type="submit" value="Verificar">
        </form>
    </div>
</div>
